"""Install and configure the bundled paper-search-pro report tool."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import shutil
import sys

from .config import Config, DEFAULT_BASE_DIR

PACKAGED_BUNDLED = "packaged_bundled"
REPO_TOOLS_FALLBACK = "repo_tools_fallback"

REQUIRED_TOOL_SENTINELS = (
    "SKILL.md",
    "README.md",
    "LICENSE.txt",
    "NOTICE.md",
    "THIRD_PARTY.md",
    "assets/webartifacts_app/paper-report/bundle.html",
    "scripts/html_renderer_webartifacts.py",
    "scripts/data_materialization.py",
)


@dataclass(frozen=True)
class ReportToolRuntime:
    root: Path
    source: str


@dataclass
class ReportToolInstallResult:
    bundled_root: str
    local_root: str
    output_dir: str
    command: str
    installed: bool
    credentials_path: str
    openalex_configured: bool
    semantic_scholar_configured: bool
    resource_source: str


def packaged_tool_root() -> Path:
    return Path(__file__).resolve().parent / "_bundled" / "paper-search-pro"


def repo_checkout_tool_root() -> Path | None:
    module_root = Path(__file__).resolve().parent.parent
    if not (module_root / "pyproject.toml").is_file():
        return None
    if not (module_root / "vpnsci_sustech").is_dir():
        return None
    return module_root / "tools" / "paper-search-pro"


def _missing_sentinels(root: Path) -> list[str]:
    return [relative for relative in REQUIRED_TOOL_SENTINELS if not (root / relative).is_file()]


def _is_valid_tool_root(root: Path) -> bool:
    return root.is_dir() and not _missing_sentinels(root)


def resolve_bundled_tool_root() -> ReportToolRuntime:
    packaged = packaged_tool_root()
    if _is_valid_tool_root(packaged):
        return ReportToolRuntime(packaged, PACKAGED_BUNDLED)

    repo = repo_checkout_tool_root()
    if repo and _is_valid_tool_root(repo):
        return ReportToolRuntime(repo, REPO_TOOLS_FALLBACK)

    checked = [packaged]
    if repo:
        checked.append(repo)
    details = "; ".join(f"{root}: missing {', '.join(_missing_sentinels(root)) or 'directory'}" for root in checked)
    raise FileNotFoundError(f"Bundled paper-search-pro snapshot not found or incomplete ({details})")


def bundled_tool_root() -> Path:
    return resolve_bundled_tool_root().root


def local_tool_root(config: Config | None = None) -> Path:
    return DEFAULT_BASE_DIR / "tools" / "paper-search-pro"


def _quote_command_part(value: str) -> str:
    if not value or any(ch.isspace() for ch in value):
        return '"' + value.replace('"', '\\"') + '"'
    return value


def default_seed_preview_command() -> str:
    executable = _quote_command_part(sys.executable)
    return f"{executable} -m vpnsci_sustech.paper_search_pro_adapter --seed {{seed_json}} --output-dir {{output_dir}}"


def default_report_command() -> str:
    """Backward-compatible default command for seed-only HTML preview."""

    return default_seed_preview_command()


def _report_output_dir(config: Config) -> Path:
    if config.paper_search_pro_output_dir:
        return Path(config.paper_search_pro_output_dir)
    return Path(config.cache_dir) / "search" / "reports"


def _copy_tree(src: Path, dst: Path, *, force: bool) -> bool:
    if not src.exists():
        raise FileNotFoundError(f"Bundled paper-search-pro snapshot not found: {src}")
    if dst.exists():
        if not force:
            return False
        resolved_dst = dst.resolve()
        allowed_parent = (DEFAULT_BASE_DIR / "tools").resolve()
        if allowed_parent not in [resolved_dst, *resolved_dst.parents]:
            raise RuntimeError(f"Refusing to remove path outside {allowed_parent}: {resolved_dst}")
        shutil.rmtree(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    ignore = shutil.ignore_patterns(
        ".git",
        "__pycache__",
        "*.pyc",
        "*.pyo",
        ".pytest_cache",
        "paper-search-results",
        ".cache",
    )
    shutil.copytree(src, dst, ignore=ignore)
    return True


def _yaml_quote(value: str) -> str:
    escaped = (value or "").replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def configure_paper_search_pro_credentials(config: Config | None = None) -> Path:
    """Write user-local paper-search-pro credentials from vpnsci config."""

    config = config or Config.load()
    user_config_dir = Path.home() / ".paper-search-pro"
    user_config_dir.mkdir(parents=True, exist_ok=True)
    config_path = user_config_dir / "config.yaml"
    content = "\n".join(
        [
            "# Generated by vpnsci-sustech. Do not commit this file.",
            f"openalex_email: {_yaml_quote(config.email)}",
            f"openalex_api_key: {_yaml_quote(config.openalex_api_key)}",
            f"semantic_scholar_api_key: {_yaml_quote(config.semantic_scholar_api_key)}",
            "ncbi_email: \"\"",
            "ncbi_api_key: \"\"",
            f"crossref_email: {_yaml_quote(config.email)}",
            f"output_dir: {_yaml_quote(str(Path(config.cache_dir) / 'paper-search-pro-results'))}",
            "default_tier: \"standard\"",
            "language: \"en\"",
            "cache_enabled: true",
            "cache_ttl_days: 7",
            "cache_max_size_mb: 500",
            "log_level: \"INFO\"",
            "",
        ]
    )
    config_path.write_text(content, encoding="utf-8")
    return config_path


def install_report_tool(config: Config | None = None, force: bool = False) -> ReportToolInstallResult:
    config = config or Config.load()
    runtime = resolve_bundled_tool_root()
    dst = local_tool_root(config)
    installed = _copy_tree(runtime.root, dst, force=force)
    credentials_path = configure_paper_search_pro_credentials(config)
    output_dir = _report_output_dir(config)
    output_dir.mkdir(parents=True, exist_ok=True)
    return ReportToolInstallResult(
        bundled_root=str(runtime.root),
        local_root=str(dst),
        output_dir=str(output_dir),
        command=default_report_command(),
        installed=installed,
        credentials_path=str(credentials_path),
        openalex_configured=bool(config.openalex_api_key),
        semantic_scholar_configured=bool(config.semantic_scholar_api_key),
        resource_source=runtime.source,
    )


def configure_report_tool(
    config: Config | None = None,
    force: bool = False,
    *,
    persist: bool = True,
) -> tuple[Config, ReportToolInstallResult]:
    """Install bundled runtime and write the bundled report bridge config."""

    config = config or Config.load()
    result = install_report_tool(config, force=force)
    config.paper_search_pro_root = result.local_root
    config.paper_search_pro_command = ""
    config.paper_search_pro_output_dir = result.output_dir
    if persist:
        config.save()
    return config, result


def ensure_report_tool_configured(
    config: Config | None = None,
    force: bool = False,
    *,
    persist: bool = True,
) -> Config:
    """Install local runtime copy and persist bundled report bridge defaults."""

    configured, _ = configure_report_tool(config, force=force, persist=persist)
    return configured
