"""Install and configure the bundled paper-search-pro report tool."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import shutil

from .config import Config, DEFAULT_BASE_DIR


@dataclass
class ReportToolInstallResult:
    bundled_root: str
    local_root: str
    output_dir: str
    command: str
    installed: bool
    credentials_path: str
    openalex_configured: bool
    semantic_scholar_configured: bool


def bundled_tool_root() -> Path:
    return Path(__file__).resolve().parent.parent / "tools" / "paper-search-pro"


def local_tool_root(config: Config | None = None) -> Path:
    return DEFAULT_BASE_DIR / "tools" / "paper-search-pro"


def default_seed_preview_command() -> str:
    return "python -m vpnsci_sustech.paper_search_pro_adapter --seed {seed_json} --output-dir {output_dir}"


def default_report_command() -> str:
    """Backward-compatible default command for seed-only HTML preview."""

    return default_seed_preview_command()


def _report_output_dir(config: Config) -> Path:
    if config.paper_search_pro_output_dir:
        return Path(config.paper_search_pro_output_dir)
    return Path(config.cache_dir) / "search" / "reports"


def _copy_tree(src: Path, dst: Path, *, force: bool) -> bool:
    if not src.exists():
        raise FileNotFoundError(f"Bundled paper-search-pro snapshot not found: {src}")
    if dst.exists():
        if not force:
            return False
        resolved_dst = dst.resolve()
        allowed_parent = (DEFAULT_BASE_DIR / "tools").resolve()
        if allowed_parent not in [resolved_dst, *resolved_dst.parents]:
            raise RuntimeError(f"Refusing to remove path outside {allowed_parent}: {resolved_dst}")
        shutil.rmtree(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    ignore = shutil.ignore_patterns(
        ".git",
        "__pycache__",
        "*.pyc",
        "*.pyo",
        ".pytest_cache",
        "paper-search-results",
        ".cache",
    )
    shutil.copytree(src, dst, ignore=ignore)
    return True


def _yaml_quote(value: str) -> str:
    escaped = (value or "").replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def configure_paper_search_pro_credentials(config: Config | None = None) -> Path:
    """Write user-local paper-search-pro credentials from vpnsci config."""

    config = config or Config.load()
    user_config_dir = Path.home() / ".paper-search-pro"
    user_config_dir.mkdir(parents=True, exist_ok=True)
    config_path = user_config_dir / "config.yaml"
    content = "\n".join(
        [
            "# Generated by vpnsci-sustech. Do not commit this file.",
            f"openalex_email: {_yaml_quote(config.email)}",
            f"openalex_api_key: {_yaml_quote(config.openalex_api_key)}",
            f"semantic_scholar_api_key: {_yaml_quote(config.semantic_scholar_api_key)}",
            "ncbi_email: \"\"",
            "ncbi_api_key: \"\"",
            f"crossref_email: {_yaml_quote(config.email)}",
            f"output_dir: {_yaml_quote(str(Path(config.cache_dir) / 'paper-search-pro-results'))}",
            "default_tier: \"standard\"",
            "language: \"en\"",
            "cache_enabled: true",
            "cache_ttl_days: 7",
            "cache_max_size_mb: 500",
            "log_level: \"INFO\"",
            "",
        ]
    )
    config_path.write_text(content, encoding="utf-8")
    return config_path


def install_report_tool(config: Config | None = None, force: bool = False) -> ReportToolInstallResult:
    config = config or Config.load()
    src = bundled_tool_root()
    dst = local_tool_root(config)
    installed = _copy_tree(src, dst, force=force)
    credentials_path = configure_paper_search_pro_credentials(config)
    output_dir = _report_output_dir(config)
    output_dir.mkdir(parents=True, exist_ok=True)
    return ReportToolInstallResult(
        bundled_root=str(src),
        local_root=str(dst),
        output_dir=str(output_dir),
        command=default_report_command(),
        installed=installed,
        credentials_path=str(credentials_path),
        openalex_configured=bool(config.openalex_api_key),
        semantic_scholar_configured=bool(config.semantic_scholar_api_key),
    )


def ensure_report_tool_configured(
    config: Config | None = None,
    force: bool = False,
    *,
    persist: bool = True,
) -> Config:
    """Install local runtime copy and persist report bridge defaults."""

    config = config or Config.load()
    result = install_report_tool(config, force=force)
    config.paper_search_pro_root = result.local_root
    config.paper_search_pro_command = result.command
    config.paper_search_pro_output_dir = result.output_dir
    if persist:
        config.save()
    return config
